spring:
  application:
    name: LiveScore
  datasource:
    url: jdbc:postgresql://livescore-database.chatfasc16fi.ap-southeast-1.rds.amazonaws.com:5432/livescore
    username: postgres
    password: Trungtruc05
  jpa:
    show-sql: true
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

    hibernate:
      ddl-auto: update

api:
  football:
    base-url: https://v3.football.api-sports.io
    name: api-football
    key: 321c9883431477ceaa3bd1bcbe6c0655
    host: v3.football.api-sports.io

league:
  priority-config: 39-1;140-2;135-3;78-4;61-5;2-6;3-7;848-8;88-9;203-10;40-11;94-12;179-13;5-14;307-15;144-16;13-17;11-18