spring:
  application:
    name: LiveScore
  datasource:
    url: jdbc:postgresql://localhost:5432/livescore
    username: postgres
    password: 652606
  jpa:
    show-sql: true
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

    hibernate:
      ddl-auto: update

api:
  football:
    base-url: https://v3.football.api-sports.io
    name: api-football
    key: 321c9883431477ceaa3bd1bcbe6c0655
    host: v3.football.api-sports.io